"use client";
import {useState} from "react";
import {HomeIcon,MagnifyingGlassIcon,UsersIcon,RectangleStackIcon,ArrowUpRightIcon,PhoneIcon} from "@heroicons/react/24/outline";
const leads=[
{name:"Delta Outdoor Co.",type:"Landscaping",place:"Memphis, TN",score:91,why:"Strong local reputation, but the site hides project work and the estimate action on mobile.",next:"Call",stage:"Ready"},
{name:"Northline Roofing",type:"Roofing",place:"Southaven, MS",score:86,why:"Active business with solid reviews and an outdated first impression.",next:"Research",stage:"New"},
{name:"Oak & Stone Remodeling",type:"Remodeling",place:"DeSoto County, MS",score:82,why:"Good photography is buried and service pages lack a clear quote path.",next:"Follow up",stage:"Contacted"}];
const nav=[["Today",HomeIcon],["Find leads",MagnifyingGlassIcon],["Leads",UsersIcon],["Pipeline",RectangleStackIcon]] as const;
export default function Home(){const [active,setActive]=useState("Today");return <main className="shell"><aside><div className="brand"><span>LF</span><b>Lead Finder</b></div><nav>{nav.map(([n,I])=><button key={n} className={active===n?"active":""} onClick={()=>setActive(n)}><I/>{n}</button>)}</nav><div className="sideFoot"><small>PRIVATE WORKSPACE</small><p>Built for focused outreach.</p></div></aside><section className="content"><header><div><p className="eyebrow">YOUR OUTREACH WORKSPACE</p><h1>{active}</h1></div><button className="primary" onClick={()=>setActive("Find leads")}><MagnifyingGlassIcon/>Find prospects</button></header>{active==="Today"&&<Today setActive={setActive}/>} {active==="Find leads"&&<Find/>}{active==="Leads"&&<Leads/>}{active==="Pipeline"&&<Pipeline/>}</section></main>}
function Today({setActive}:{setActive:(x:string)=>void}){return <><div className="intro"><h2>Know who deserves your attention.</h2><p>Your best prospects, follow-ups, and next moves in one place. No CRM clutter.</p></div><div className="metrics"><div><strong>3</strong><span>Ready for outreach</span></div><div><strong>2</strong><span>Follow-ups due</span></div><div><strong>1</strong><span>Interested lead</span></div></div><div className="sectionHead"><div><p className="eyebrow">PRIORITY</p><h3>Work these leads next</h3></div><button className="textBtn" onClick={()=>setActive("Leads")}>View all <ArrowUpRightIcon/></button></div><div className="leadList">{leads.map((l,i)=><article className="lead" key={l.name}><div className="rank">0{i+1}</div><div className="leadMain"><div className="leadTop"><div><h4>{l.name}</h4><p>{l.type} · {l.place}</p></div><div className="score"><b>{l.score}</b><span>FIT</span></div></div><p className="why">{l.why}</p><div className="leadBottom"><span className="status">{l.stage}</span><span>Next: <b>{l.next}</b></span><button>Open brief <ArrowUpRightIcon/></button></div></div></article>)}</div></>}
function Find(){return <><div className="intro"><h2>Find businesses worth contacting.</h2><p>Start broad. Research only the prospects that show real opportunity.</p></div><div className="searchPanel"><label>BUSINESS TYPE<input placeholder="Landscapers"/></label><label>AREA<input placeholder="Memphis, TN"/></label><label>RESULTS<select defaultValue="25"><option>10</option><option>25</option><option>50</option></select></label><button className="primary">Search businesses</button></div><div className="empty"><MagnifyingGlassIcon/><h3>Your next client starts here.</h3><p>Search by business type and area. Results will be screened before deeper research.</p></div></>}
function Leads(){return <><div className="intro"><h2>Qualified prospects.</h2><p>Research, prepare your angle, then make the contact yourself.</p></div><div className="table">{leads.map(l=><div className="row" key={l.name}><div><b>{l.name}</b><span>{l.type} · {l.place}</span></div><span className="status">{l.stage}</span><strong>{l.score}</strong><button>Research <ArrowUpRightIcon/></button></div>)}</div></>}
function Pipeline(){const cols=["Researching","Ready","Contacted","Interested","Proposal","Won"];return <><div className="intro"><h2>Keep every opportunity moving.</h2><p>Every active lead should have a clear next action.</p></div><div className="pipeline">{cols.map((c,i)=><div className="col" key={c}><div className="colHead"><b>{c}</b><span>{i<3?1:0}</span></div>{i<3&&<div className="mini"><small>{leads[i].type}</small><h4>{leads[i].name}</h4><p>{leads[i].place}</p><div><PhoneIcon/><span>{leads[i].next}</span></div></div>}</div>)}</div></>}